//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        public commande()
        {
            // Initialisez vos valeurs par défaut ici
            this.id = 0;
            this.produits = null;
            this.date_commande = DateTime.Now; // Exemple : Date de commande par défaut est la date actuelle
            this.etat_commande = "En attente"; // Exemple : État de commande par défaut est "En attente"
        }

        public int id_commande { get; set; }
        public string nom { get; set; }
        public string adresse { get; set; }
        public string ville { get; set; }
        public string code_postal { get; set; }
        public string produits { get; set; }
        public int? id { get; set; }
        public string paiement { get; set; }
        public DateTime? date_commande { get; set; }
        public TimeSpan? heure_commande { get; set; }
        public string etat_commande { get; set; }
    }
}
